# Generated by Django 2.1.7 on 2019-03-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_auto_20190324_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
